import type { Metadata } from "next";
import { Sen } from "next/font/google";
import "./globals.scss";
import { Header } from "@/shared/ui/header";

const sen = Sen({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Robin W.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sen.className}>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
